
export default {
  'js': 'text/javascript',
  'json': 'application/json',
  'pdf': 'application/pdf',
  'sql': 'application/sql',
  'xml': 'application/xml',
  'zip': 'application/zip',
  'txt': 'text/plain',
  'mpeg': 'audio/mpeg',
  'mpg': 'audio/mpeg',
  'avif': 'image/avif',
  'jpg': 'image/jpeg',
  'jpeg': 'image/jpeg',
  'html': 'text/html',
  'ogg': 'audio/ogg',
  'png': 'image/png',
  'css': 'text/css',
  'csv': 'text/csv',
  'xml': 'text/xml',
}
